'''
Triangular, pentagonal, and hexagonal
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

from math import sqrt
count = 0
i, t, p, h = 0, 0, 0, 0

while (count < 3):
    i = i + 1
    t = (i * (i + 1)) // 2

    # check penta
    p = 0
    s = sqrt(24 * t + 1)
    if s == int(s):
        x = (1 + s) / 6
        if x == int(x):
            p = int(x)
    h = 0
    if p > 0:
        # the number is penta , now try hexa
        s2 = sqrt(8 * t + 1)
        if s2 == int(s2):
            x = (1 + s2) / 4
            if x == int(x):
                count = count + 1
                h = int(x)
                print(" i = ", i, " tri = ", t, " p =", p, " h =", h)

    if i % 1000 == 0 or i == 285:
        print(i, ' ', t)
